// Relative import so the seed script can run this file outside Next's alias.
import type { AppPost, ShopPost, Profile } from "../types";

/** Seeded local data — the Beta Board reads this, never the network. */

const maya: Profile = {
  id: "p-maya",
  handle: "mayabuilds",
  displayName: "Maya Torres",
  campus: "ucsc",
  verified: true,
  avatarColor: "tomato",
};

const kenzo: Profile = {
  id: "p-kenzo",
  handle: "kenzo.dev",
  displayName: "Kenzo Park",
  campus: "ucsc",
  verified: true,
  avatarColor: "link-blue",
};

const priya: Profile = {
  id: "p-priya",
  handle: "priya.ships",
  displayName: "Priya Raman",
  campus: "ucsc",
  verified: true,
  avatarColor: "grape",
};

const ossslug: Profile = {
  id: "p-ossslug",
  handle: "ossslug",
  displayName: "Open Slug Collective",
  campus: "ucsc",
  verified: true,
  avatarColor: "live-green",
};

const dormdev: Profile = {
  id: "p-dormdev",
  handle: "dorm.dev",
  displayName: "Eli Nakamura",
  campus: "ucsc",
  verified: true,
  avatarColor: "gold",
};

const mossgirl: Profile = {
  id: "p-mossgirl",
  handle: "mossgirl",
  displayName: "Fern Okafor",
  campus: "ucsc",
  verified: true,
  avatarColor: "live-green",
};

export const apps: AppPost[] = [
  {
    id: "app-slugroute",
    type: "app",
    author: maya,
    title: "SlugRoute",
    description: "Live Metro + Loop bus tracking that actually knows about the rain detours.",
    upvotes: 47,
    createdAt: "2026-06-28T18:20:00Z",
    platform: "ios",
    status: "shipped_weekend",
    statusLabel: "Shipped this weekend",
    ctaLabel: "Join TestFlight",
    ctaUrl: "https://testflight.apple.com/join/slugroute",
    bannerColor: "link-blue",
    tags: ["shipped-this-weekend", "campus-essentials"],
    boosted: true,
  },
  {
    id: "app-dininghall",
    type: "app",
    author: kenzo,
    title: "DiningHall.fyi",
    description: "Tonight's menus for all five halls, ranked by how fast the line moves.",
    upvotes: 39,
    createdAt: "2026-06-21T02:10:00Z",
    platform: "web",
    status: "live",
    statusLabel: "Campus essential",
    ctaLabel: "View on Web",
    ctaUrl: "https://dininghall.fyi",
    bannerColor: "live-green",
    tags: ["campus-essentials"],
  },
  {
    id: "app-overcommit",
    type: "app",
    author: priya,
    title: "Overcommit",
    description: "A gentle accountability tracker for the 6 clubs you definitely joined.",
    upvotes: 24,
    createdAt: "2026-06-30T21:45:00Z",
    platform: "ios",
    status: "needs_testers",
    statusLabel: "Needs 12 testers",
    ctaLabel: "Join TestFlight",
    ctaUrl: "https://testflight.apple.com/join/overcommit",
    bannerColor: "grape",
    tags: ["beta-testers-needed", "open-source"],
    testersNeeded: 12,
  },
  {
    id: "app-redwoodfeed",
    type: "app",
    author: ossslug,
    title: "Redwood Feed",
    description: "One open-source firehose for every club calendar, flyer, and free-food ping.",
    upvotes: 31,
    createdAt: "2026-06-25T16:00:00Z",
    platform: "web",
    status: "live",
    statusLabel: "Open source",
    ctaLabel: "View on Web",
    ctaUrl: "https://github.com/ossslug/redwood-feed",
    bannerColor: "tomato",
    tags: ["open-source", "campus-essentials"],
  },
  {
    id: "app-spincycle",
    type: "app",
    author: dormdev,
    title: "SpinCycle",
    description: "Which dorm washers are free right now — and a ping when yours is done.",
    upvotes: 52,
    createdAt: "2026-06-28T04:30:00Z",
    platform: "web",
    status: "beta_full",
    statusLabel: "Beta full",
    ctaLabel: "Join waitlist",
    ctaUrl: "https://spincycle.app/waitlist",
    bannerColor: "gold",
    tags: ["shipped-this-weekend", "campus-essentials"],
  },
  {
    id: "app-ferngully",
    type: "app",
    author: mossgirl,
    title: "Fern Gully",
    description: "Crowd-mapped study spots in the redwoods, rated by shade, wifi, and banana slugs.",
    upvotes: 18,
    createdAt: "2026-07-01T19:05:00Z",
    platform: "ios",
    status: "needs_testers",
    statusLabel: "Needs 8 testers",
    ctaLabel: "Join TestFlight",
    ctaUrl: "https://testflight.apple.com/join/ferngully",
    bannerColor: "live-green",
    tags: ["beta-testers-needed", "open-source"],
    testersNeeded: 8,
  },
];

// ---------------------------------------------------------------------------
// Marketplace ('shop') — 6 recurring student sellers. Fallback data when env
// is empty; the live market reads Supabase. (Thrift has no fixtures — the
// thrift feed returns [] without a database.)
// ---------------------------------------------------------------------------

const petalpress: Profile = {
  id: "p-petalpress",
  handle: "petalpress",
  displayName: "Ivy Chen",
  campus: "ucsc",
  verified: true,
  avatarColor: "grape",
};

const mudslinger: Profile = {
  id: "p-mudslinger",
  handle: "mudslinger",
  displayName: "Theo Alvarez",
  campus: "ucsc",
  verified: true,
  avatarColor: "tomato",
};

const stickyslug: Profile = {
  id: "p-stickyslug",
  handle: "stickyslug",
  displayName: "June Park",
  campus: "ucsc",
  verified: true,
  avatarColor: "gold",
};

const foldedpine: Profile = {
  id: "p-foldedpine",
  handle: "foldedpine",
  displayName: "Rowan Diaz",
  campus: "ucsc",
  verified: true,
  avatarColor: "live-green",
};

const waxpoetic: Profile = {
  id: "p-waxpoetic",
  handle: "waxpoetic",
  displayName: "Sana Okafor",
  campus: "ucsc",
  verified: true,
  avatarColor: "link-blue",
};

const hookedslug: Profile = {
  id: "p-hookedslug",
  handle: "hookedslug",
  displayName: "Milo Tran",
  campus: "ucsc",
  verified: true,
  avatarColor: "grape",
};

export const shopListings: ShopPost[] = [
  {
    id: "prod-slugstem",
    type: "shop",
    author: petalpress,
    title: "Slug & Stem",
    description: "Dried-flower bouquets foraged (ethically) from the meadow edges.",
    upvotes: 34,
    createdAt: "2026-06-27T17:00:00Z",
    priceCents: 1800,
    category: "flowers",
    status: "in_stock",
    statusLabel: "3 left",
    bannerColor: "grape",
    locationLabel: "Porter Meadow",
    tags: ["flowers"],
    reviewCount: 0,
  },
  {
    id: "prod-kilnkelp",
    type: "shop",
    author: mudslinger,
    title: "Kiln & Kelp",
    description: "Hand-thrown mugs glazed in fog gradients. Every one is lopsided on purpose.",
    upvotes: 41,
    createdAt: "2026-06-24T20:30:00Z",
    priceCents: 3200,
    category: "ceramics",
    status: "made_to_order",
    statusLabel: "Made to order",
    bannerColor: "tomato",
    locationLabel: "Merrill kilnyard",
    tags: ["ceramics"],
    reviewCount: 0,
  },
  {
    id: "prod-slugstickers",
    type: "shop",
    author: stickyslug,
    title: "Banana Slug Stickers",
    description: "Waterproof vinyl slugs for laptops, water bottles, and parking permits.",
    upvotes: 58,
    createdAt: "2026-06-29T15:10:00Z",
    priceCents: 600,
    category: "stickers",
    status: "in_stock",
    statusLabel: "Fresh batch",
    bannerColor: "gold",
    locationLabel: "Quarry Plaza",
    tags: ["stickers"],
    reviewCount: 0,
  },
  {
    id: "prod-redwoodreads",
    type: "shop",
    author: foldedpine,
    title: "Redwood Reads",
    description: "Hand-bound journals with recycled paper and bark-pressed covers.",
    upvotes: 27,
    createdAt: "2026-06-26T19:45:00Z",
    priceCents: 2400,
    category: "journals",
    status: "in_stock",
    statusLabel: "5 left",
    bannerColor: "live-green",
    locationLabel: "McHenry steps",
    tags: ["journals"],
    reviewCount: 0,
  },
  {
    id: "prod-fogcandle",
    type: "shop",
    author: waxpoetic,
    title: "Fog Candle Co.",
    description: "Soy candles in scents like First Rain, Eucalyptus Grove, and Dining Hall Waffle.",
    upvotes: 45,
    createdAt: "2026-06-28T22:15:00Z",
    priceCents: 1500,
    category: "candles",
    status: "sold_out",
    statusLabel: "Sold out",
    bannerColor: "link-blue",
    locationLabel: "Cowell mailroom",
    tags: ["candles"],
    reviewCount: 0,
  },
  {
    id: "prod-loopthreads",
    type: "shop",
    author: hookedslug,
    title: "Loop Threads",
    description: "Chunky crochet beanies in banana-slug yellow. Warm enough for the fog line.",
    upvotes: 22,
    createdAt: "2026-07-01T16:40:00Z",
    priceCents: 2200,
    category: "fiber",
    status: "made_to_order",
    statusLabel: "Made to order",
    bannerColor: "gold",
    locationLabel: "Bay Tree pickup",
    tags: ["fiber"],
    reviewCount: 0,
  },
];
